version: '3'

services:

  #############################################################
  ######################### DATABASES #########################
  #############################################################

  db-tic-tac-toe:
    container_name: db-tic-tac-toe
    image: postgres
    restart: always
    hostname: db-tic-tac-toe
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tic-tac-toe
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game
      PGDATA: /tmp
    volumes:
      - ./docker/postgres/data-tic-tac-toe:/var/lib/postgresql/data

  #############################################################
  ######################### KAFKA #############################
  #############################################################

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1